{{ if .Values.license }}
{{ if .Values.gateway.enable }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-gateway-route
  labels: {{- include "api-pod.labels" . | nindent 5 }}
spec:
  {{ if .Values.gateway.hostname }}
  host: {{ .Values.gateway.hostname }}
  {{ end }}
  to:
    kind: Service
    name: {{ .Release.Name }}-gateway-service
  port:
    targetPort: 9443
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
{{ end }}
{{ end }}
