{{ if .Values.license }}
{{ if .Values.pem.enable }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-pem-route
  labels: {{- include "pem-pod.labels" . | nindent 5 }}
spec:
  {{ if .Values.pem.hostname }}
  host: {{ .Values.pem.hostname }}
  {{ end }}
  to:
    kind: Service
    name: {{ .Release.Name }}-pem-service
  port:
    targetPort: 9443
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
{{ end }}
