{{ if .Values.license }}
{{ if .Values.pp.enable }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-pp-route
  labels: {{- include "pp-pod.labels" . | nindent 5 }}
spec:
  {{ if .Values.pp.hostname }}
  host: {{ .Values.pp.hostname }}
  {{ end }}
  to:
    kind: Service
    name: {{ .Release.Name }}-pp-service
  port:
    targetPort: 9443
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
{{ end }}
